<?php
return [
    'palabras' => [
        "GATO",
        "PERRO",
        "CASA",
        "ARBOL",
        "AGUA",
        "FUEGO",
        "TIERRA",
        "VIENTO",
        "SOL",
        "LUNA",
        "ESTRELLA",
        "MAR",
        "NUBE",
        "LLUVIA",
        "NIEVE",
        "MONTAÑA",
        "RIO",
        "BOSQUE",
        "JARDIN",
        "FLOR",
        "MADRID",
        "PARIS",
        "LONDRES",
        "ROMA",
        "BERLIN",
        "LISBOA",
        "ATENAS",
        "CAIRO",
        "TOKIO",
        "PEKIN",
        "MEXICO",
        "ARGENTINA",
        "BRASIL",
        "CHILE",
        "PERU",
        "COLOMBIA",
        "VENEZUELA",
        "ECUADOR",
        "BOLIVIA",
        "URUGUAY",
        "MANZANA",
        "PERA",
        "NARANJA",
        "PLATANO",
        "FRESA",
        "SANDIA",
        "UVAS",
        "MELON",
        "PINA",
        "MANGO",
        "FUTBOL",
        "BASQUET",
        "TENIS",
        "NATACION",
        "ATLETISMO",
        "CICLISMO",
        "VOLEIBOL",
        "BEISBOL",
        "RUGBY",
        "GOLF",
        "ROJO",
        "AZUL",
        "VERDE",
        "AMARILLO",
        "BLANCO",
        "NEGRO",
        "GRIS",
        "MARRON",
        "ROSADO",
        "MORADO",
        "ALEGRIA",
        "TRISTEZA",
        "AMOR",
        "ODIO",
        "CALMA",
        "IRA",
        "MIEDO",
        "SORPRESA",
        "CANSANCIO",
        "ENERGIA",
        "LIBRO",
        "CUADERNO",
        "LAPIZ",
        "BOLIGRAFO",
        "BORRADOR",
        "REGLAS",
        "MOCHILA",
        "ESTUCHE",
        "PIZARRA",
        "TIZA",
        "MEDICO",
        "ENFERMERA",
        "DENTISTA",
        "VETERINARIO",
        "ABOGADO",
        "PROFESOR",
        "INGENIERO",
        "ARQUITECTO",
        "COCINERO",
        "CARPINTERO",
        "FAMILIA",
        "PADRE",
        "MADRE",
        "HERMANO",
        "HERMANA",
        "HIJO",
        "HIJA",
        "ABUELO",
        "ABUELA",
        "TIO",
        "CIUDAD",
        "PUEBLO",
        "CALLE",
        "AVENIDA",
        "PLAZA",
        "PARQUE",
        "PUENTE",
        "EDIFICIO",
        "HOSPITAL",
        "ESCUELA",
        "CINE",
        "TEATRO",
        "MUSEO",
        "BIBLIOTECA",
        "IGLESIA",
        "MERCADO",
        "BANCO",
        "FARMACIA",
        "PANADERIA",
        "CARNICERIA",
        "DIA",
        "NOCHE",
        "MAÑANA",
        "TARDE",
        "HORA",
        "MINUTO",
        "SEGUNDO",
        "SEMANA",
        "MES",
        "AÑO",
        "PRIMAVERA",
        "VERANO",
        "OTOÑO",
        "INVIERNO",
        "CALOR",
        "FRIO",
        "NIEBLA",
        "HUMEDAD",
        "DESAYUNO",
        "ALMUERZO",
        "CENA",
        "MERIENDA",
        "PAN",
        "QUESO",
        "JAMON",
        "HUEVO",
        "LECHE",
        "ZUMO",
        "PESCADO",
        "POLLO",
        "CARNE",
        "VERDURAS",
        "LEGUMBRES",
        "PASTA",
        "ARROZ",
        "SOPA",
        "ENSALADA",
        "FRUTA",
        "OCEANO",
        "BOMBERO",
        "POLICIA",
        "AMBULANCIA",
        "EMERGENCIA",
        "PELIGRO",
        "SEGURIDAD",
        "PROTECCION",
        "AUXILIO",
        "RESCATE",
        "INTERNET",
        "COMPUTADORA",
        "TECLADO",
        "PANTALLA",
        "RATON",
        "IMPRESORA",
        "SONIDO",
        "VIDEO",
        "JUEGO",
        "PROGRAMA",
        "AVION",
        "TREN",
        "AUTOBUS",
        "COCHE",
        "BARCO",
        "BICICLETA",
        "MOTO",
        "TAXI",
        "METRO",
        "TRANVIA",
        "CAMPO",
        "PLAYA",
        "LAGO",
        "ISLA",
        "PENINSULA",
        "DESIERTO",
        "JUNGLA",
        "SABANA",
        "POLO",
        "FELIZ",
        "ENOJADO",
        "TRANQUILO",
        "PREOCUPADO",
        "SORPRENDIDO",
        "EMOCIONADO",
        "NERVIOSO",
        "RELAJADO",
        "CONTENTO",
        "TRISTE",
        "CORAZON",
        "CEREBRO",
        "PULMONES",
        "RIÑONES",
        "ESTOMAGO",
        "INTESTINOS",
        "HUESOS",
        "MUSCULOS",
        "PIEL",
        "SANGRE",
        "MIRAR",
        "ESCUCHAR",
        "HABLAR",
        "CAMINAR",
        "CORRER",
        "SALTAR",
        "COMER",
        "BEBER",
        "DORMIR",
        "DESPERTAR",
        "AMIGO",
        "VECINO",
        "COMPAÑERO",
        "COLEGA",
        "ALUMNO",
        "MAESTRO",
        "ESTUDIANTE",
        "PROFESIONAL",
        "ARTISTA",
        "MUSICO",
        "DULCE",
        "SALADO",
        "AMARGO",
        "ACIDO",
        "PICANTE",
        "FRESCO",
        "CALIENTE",
        "SUAVE",
        "DURO",
        "GRANDE",
        "PEQUEÑO",
        "ALTO",
        "BAJO",
        "ANCHO",
        "ESTRECHO",
        "LARGO",
        "CORTO",
        "PESADO",
        "LIGERO",
        "CLARO",
        "OSCURO",
        "BRILLANTE",
        "OPACO",
        "RAPIDO",
        "LENTO",
        "FUERTE",
        "DEBIL",
        "SALUDABLE",
        "ENFERMO",
        "VOLCAN",
        "CASCADA",
        "ESTANQUE",
        "GLACIAR",
    ],

    // Pistas para el Crucigrama. Solo hace falta cargar pista a las
    // palabras que quieras que puedan aparecer en el crucigrama;
    // la Sopa de Letras no usa este array.
    'pistas' => [
        'GATO' => 'Felino doméstico que ronronea',
        'PERRO' => 'El mejor amigo del hombre',
        'CASA' => 'Vivienda familiar',
        'ARBOL' => 'Tiene tronco, ramas y raíces',
        'AGUA' => 'H2O',
        'FUEGO' => 'Arde y da calor',
        'VIENTO' => 'Aire en movimiento',
        'SOL' => 'Estrella que ilumina la Tierra de día',
        'LUNA' => 'Satélite natural de la Tierra',
        'ESTRELLA' => 'Punto brillante en el cielo nocturno',
        'MAR' => 'Gran masa de agua salada',
        'NUBE' => 'Flota en el cielo antes de la lluvia',
        'LLUVIA' => 'Cae del cielo, gota a gota',
        'NIEVE' => 'Copos blancos y fríos',
        'RIO' => 'Corriente de agua que va al mar',
        'BOSQUE' => 'Muchos árboles juntos',
        'JARDIN' => 'Se cultivan flores y plantas',
        'FLOR' => 'Nace en el tallo, tiene pétalos',
        'MADRID' => 'Capital de España',
        'PARIS' => 'Capital de Francia',
        'LONDRES' => 'Capital del Reino Unido',
        'ROMA' => 'Capital de Italia',
        'TOKIO' => 'Capital de Japón',
        'MEXICO' => 'País de Norteamérica, capital CDMX',
        'BRASIL' => 'El país más grande de Sudamérica',
        'CHILE' => 'País largo y angosto de Sudamérica',
        'PERU' => 'País de Machu Picchu',
        'URUGUAY' => 'País entre Argentina y Brasil',
        'MANZANA' => 'Fruta roja o verde, ronda de Newton',
        'PERA' => 'Fruta con forma característica, más ancha abajo',
        'NARANJA' => 'Fruta cítrica, también un color',
        'FRESA' => 'Fruta roja pequeña con semillas por fuera',
        'MANGO' => 'Fruta tropical dulce',
        'FUTBOL' => 'Deporte de 11 contra 11 con pelota',
        'TENIS' => 'Se juega con raqueta y pelota amarilla',
        'GOLF' => 'Deporte de palos y hoyos',
        'ROJO' => 'Color de la sangre',
        'AZUL' => 'Color del cielo despejado',
        'VERDE' => 'Color de las hojas',
        'BLANCO' => 'Color de la nieve',
        'NEGRO' => 'Ausencia de todo color',
        'GRIS' => 'Mezcla de blanco y negro',
        'AMOR' => 'Sentimiento opuesto al odio',
        'MIEDO' => 'Sensación ante el peligro',
        'ENERGIA' => 'Capacidad de hacer trabajo',
        'LIBRO' => 'Se lee página por página',
        'LAPIZ' => 'Se escribe y se puede borrar',
        'MOCHILA' => 'Se lleva en la espalda',
        'TIZA' => 'Se usa para escribir en el pizarrón',
        'MEDICO' => 'Atiende pacientes en un hospital',
        'ABOGADO' => 'Profesional del derecho',
        'PROFESOR' => 'Enseña en el aula',
        'INGENIERO' => 'Diseña y construye soluciones técnicas',
        'FAMILIA' => 'Padres, hijos y demás parientes',
        'PADRE' => 'Progenitor masculino',
        'MADRE' => 'Progenitora',
        'HERMANO' => 'Hijo de los mismos padres, varón',
        'HIJO' => 'Descendiente varón',
        'ABUELO' => 'Padre del padre o de la madre',
        'CIUDAD' => 'Núcleo urbano grande',
        'CALLE' => 'Vía entre edificios',
        'AVENIDA' => 'Calle ancha y principal',
        'PLAZA' => 'Espacio público central de un pueblo',
        'PARQUE' => 'Zona verde para pasear',
        'PUENTE' => 'Cruza un río o una vía',
        'EDIFICIO' => 'Construcción de varios pisos',
        'HOSPITAL' => 'Ahí atienden a los enfermos',
        'ESCUELA' => 'Ahí se enseña a los chicos',
        'CINE' => 'Ahí se ven películas en pantalla grande',
        'TEATRO' => 'Ahí se representan obras en vivo',
        'MUSEO' => 'Guarda y exhibe obras de arte o historia',
        'IGLESIA' => 'Templo cristiano',
        'MERCADO' => 'Ahí se compran alimentos frescos',
        'FARMACIA' => 'Ahí se compran medicamentos',
        'PANADERIA' => 'Ahí se compra el pan',
        'CARNICERIA' => 'Ahí se compra la carne',
        'DIA' => 'Opuesto de noche',
        'NOCHE' => 'Cuando sale la luna',
        'TARDE' => 'Entre el mediodía y la noche',
        'HORA' => 'Tiene 60 minutos',
        'SEMANA' => 'Tiene siete días',
        'MES' => 'Puede tener 28, 30 o 31 días',
        'AÑO' => 'Doce meses',
        'VERANO' => 'La estación más calurosa',
        'INVIERNO' => 'La estación más fría',
        'CALOR' => 'Sensación de temperatura alta',
        'FRIO' => 'Sensación de temperatura baja',
        'PAN' => 'Se hace con harina y se hornea',
        'QUESO' => 'Se hace con leche cuajada',
        'HUEVO' => 'Lo pone la gallina',
        'LECHE' => 'La da la vaca',
        'POLLO' => 'Ave de granja, muy consumida',
        'CARNE' => 'Alimento de origen animal',
        'ARROZ' => 'Grano blanco, base de muchos platos',
        'SOPA' => 'Plato caliente y líquido',
        'FRUTA' => 'Se cosecha de árboles y plantas, es dulce',
        'OCEANO' => 'Masa de agua salada más grande que el mar',
        'BOMBERO' => 'Apaga incendios',
        'POLICIA' => 'Vela por la seguridad y el orden público',
        'AMBULANCIA' => 'Traslada heridos y enfermos con urgencia',
        'EMERGENCIA' => 'Situación que requiere atención inmediata',
        'PELIGRO' => 'Riesgo de que algo malo pase',
        'SEGURIDAD' => 'Ausencia de riesgo',
        'AUXILIO' => 'Grito de pedido de ayuda',
        'RESCATE' => 'Operación para salvar a alguien en peligro',
        'INTERNET' => 'Red global de computadoras interconectadas',
        'COMPUTADORA' => 'Procesa datos, tiene teclado y pantalla',
        'TECLADO' => 'Se usa para escribir en la computadora',
        'PANTALLA' => 'Muestra imágenes en un dispositivo',
        'SONIDO' => 'Lo que percibe el oído',
        'AVION' => 'Vuela y transporta pasajeros por el aire',
        'TREN' => 'Circula sobre vías, en vagones',
        'COCHE' => 'Vehículo de cuatro ruedas',
        'BARCO' => 'Navega sobre el agua',
        'BICICLETA' => 'Vehículo de dos ruedas a pedal',
        'MOTO' => 'Vehículo de dos ruedas a motor',
        'TAXI' => 'Auto de alquiler con conductor',
        'METRO' => 'Tren subterráneo urbano',
        'PLAYA' => 'Orilla de arena junto al mar',
        'LAGO' => 'Masa de agua rodeada de tierra',
        'ISLA' => 'Tierra rodeada de agua por todos lados',
        'DESIERTO' => 'Región árida con muy poca agua',
        'FELIZ' => 'Estado de ánimo alegre',
        'TRANQUILO' => 'Sin nervios ni agitación',
        'NERVIOSO' => 'Inquieto, con ansiedad',
        'TRISTE' => 'Estado de ánimo apenado',
        'CORAZON' => 'Órgano que bombea la sangre',
        'CEREBRO' => 'Órgano que controla el cuerpo, en la cabeza',
        'PULMONES' => 'Órganos con los que respiramos',
        'HUESOS' => 'Forman el esqueleto',
        'PIEL' => 'Órgano que cubre todo el cuerpo',
        'SANGRE' => 'Líquido rojo que circula por las venas',
        'MIRAR' => 'Usar la vista para observar',
        'ESCUCHAR' => 'Usar el oído para percibir sonidos',
        'HABLAR' => 'Comunicarse con la voz',
        'CAMINAR' => 'Desplazarse a pie',
        'CORRER' => 'Caminar rápido, a paso veloz',
        'COMER' => 'Ingerir alimentos',
        'DORMIR' => 'Descansar con los ojos cerrados',
        'AMIGO' => 'Persona de confianza, no familiar',
        'VECINO' => 'Vive cerca de tu casa',
        'ALUMNO' => 'Va a la escuela a aprender',
        'MAESTRO' => 'Enseña en la escuela primaria',
        'ARTISTA' => 'Se dedica a una expresión creativa',
        'MUSICO' => 'Toca un instrumento o compone canciones',
        'DULCE' => 'Sabor del azúcar',
        'SALADO' => 'Sabor de la sal',
        'ACIDO' => 'Sabor del limón',
        'PICANTE' => 'Sabor que arde en la boca',
        'CALIENTE' => 'Opuesto de frío',
        'SUAVE' => 'Opuesto de áspero',
        'DURO' => 'Opuesto de blando',
        'GRANDE' => 'Opuesto de pequeño',
        'ALTO' => 'Opuesto de bajo',
        'BAJO' => 'Opuesto de alto',
        'LARGO' => 'Opuesto de corto',
        'CORTO' => 'Opuesto de largo',
        'PESADO' => 'Opuesto de liviano',
        'LIGERO' => 'Opuesto de pesado',
        'CLARO' => 'Opuesto de oscuro',
        'OSCURO' => 'Opuesto de claro',
        'RAPIDO' => 'Opuesto de lento',
        'LENTO' => 'Opuesto de rápido',
        'FUERTE' => 'Opuesto de débil',
        'DEBIL' => 'Opuesto de fuerte',
        'VOLCAN' => 'Montaña que puede erupcionar lava',
        'CASCADA' => 'Caída de agua desde altura',
        'GLACIAR' => 'Gran masa de hielo que se mueve lentamente',
    ],
];
